# Generated by Django 5.1.6 on 2025-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debitcards',
            fields=[
                ('debitcardid', models.UUIDField(db_column='debitcardID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('ifsc_code', models.TextField(blank=True, db_column='IFSC_code', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('dues', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('maxdailylimit', models.DecimalField(blank=True, db_column='maxDailyLimit', decimal_places=65535, max_digits=65535, null=True)),
                ('weeklylimit', models.DecimalField(blank=True, db_column='weeklyLimit', decimal_places=65535, max_digits=65535, null=True)),
                ('cardno', models.TextField(db_column='cardNo', unique=True)),
            ],
            options={
                'db_table': 'debitCards',
                'db_table_comment': 'credit card details',
                'managed': False,
            },
        ),
    ]
